server:
  address: 127.0.0.1
  port: 8081

flow-mind:
  platform:
    enabled: true
    sqlite:
      path: ./data/business-flow.db
    mock:
      enabled: false
    callback:
      async-enabled: true
    timeout-scan:
      enabled: true
  business: {}

server.servlet.session:
  timeout: 480m
  cookie:
    http-only: true
    same-site: lax
    path: /
