package com.flowmind.platform.api.error;

/**
 * 平台公共 Service 可能返回的稳定错误码。
 *
 * @author FlowMind
 * @since 2026-08-10
 */
public final class PlatformErrorCodes {

    public static final String REQUEST_INVALID = "FLOW_REQUEST_INVALID";
    public static final String STATE_INVALID = "FLOW_STATE_INVALID";
    public static final String DATABASE_BUSY = "FLOW_DATABASE_BUSY";
    public static final String DATABASE_ERROR = "FLOW_DATABASE_ERROR";
    public static final String DEFINITION_NOT_FOUND = "FLOW_DEFINITION_NOT_FOUND";
    public static final String DEFINITION_NOT_ACTIVE = "FLOW_DEFINITION_NOT_ACTIVE";
    public static final String DEFINITION_INVALID = "FLOW_DEFINITION_INVALID";
    public static final String NODE_NOT_FOUND = "FLOW_NODE_NOT_FOUND";
    public static final String INVALID_ACTION = "FLOW_INVALID_ACTION";
    public static final String OPERATION_ID_REQUIRED = "FLOW_OPERATION_ID_REQUIRED";
    public static final String OPERATION_ID_CONFLICT = "FLOW_OPERATION_ID_CONFLICT";
    public static final String OPERATION_IN_PROGRESS = "FLOW_OPERATION_IN_PROGRESS";
    public static final String APPROVER_RESOLVE_FAILED = "FLOW_APPROVER_RESOLVE_FAILED";
    public static final String OPERATOR_REQUIRED = "FLOW_OPERATOR_REQUIRED";
    public static final String INSTANCE_NOT_FOUND = "FLOW_INSTANCE_NOT_FOUND";
    public static final String INSTANCE_STATUS_INVALID = "FLOW_INSTANCE_STATUS_INVALID";
    public static final String TASK_NOT_FOUND = "FLOW_TASK_NOT_FOUND";
    public static final String TASK_NOT_ACTIVE = "FLOW_TASK_NOT_ACTIVE";
    public static final String TASK_PERMISSION_DENIED = "FLOW_TASK_PERMISSION_DENIED";
    public static final String ADMIN_PERMISSION_DENIED = "FLOW_ADMIN_PERMISSION_DENIED";
    public static final String TASK_STATUS_INVALID = "FLOW_TASK_STATUS_INVALID";
    public static final String TASK_CONCURRENT_MODIFIED = "FLOW_TASK_CONCURRENT_MODIFIED";
    public static final String TASK_GROUP_NOT_FOUND = "FLOW_TASK_GROUP_NOT_FOUND";
    public static final String TASK_GROUP_STATUS_INVALID = "FLOW_TASK_GROUP_STATUS_INVALID";
    public static final String TASK_GROUP_CONCURRENT_MODIFIED = "FLOW_TASK_GROUP_CONCURRENT_MODIFIED";
    public static final String GATEWAY_NO_MATCH = "FLOW_GATEWAY_NO_MATCH";
    public static final String GATEWAY_CONFIG_INVALID = "FLOW_GATEWAY_CONFIG_INVALID";
    public static final String PARALLEL_GROUP_NOT_FOUND = "FLOW_PARALLEL_GROUP_NOT_FOUND";
    public static final String PARALLEL_JOIN_CONFLICT = "FLOW_PARALLEL_JOIN_CONFLICT";
    public static final String NODE_CONFIG_INVALID = "FLOW_RUNTIME_NODE_CONFIG_INVALID";
    public static final String CALLBACK_EVENT_CONFLICT = "FLOW_CALLBACK_EVENT_CONFLICT";
    public static final String HISTORY_ARCHIVE_INVALID = "FLOW_HISTORY_ARCHIVE_INVALID";
    public static final String ATTACHMENT_REQUIRED = "FLOW_ATTACHMENT_REQUIRED";
    public static final String ATTACHMENT_TYPE_NOT_ALLOWED = "FLOW_ATTACHMENT_TYPE_NOT_ALLOWED";
    public static final String ATTACHMENT_TOO_LARGE = "FLOW_ATTACHMENT_TOO_LARGE";
    public static final String ATTACHMENT_PERMISSION_DENIED = "FLOW_ATTACHMENT_PERMISSION_DENIED";
    public static final String ATTACHMENT_NOT_FOUND = "FLOW_ATTACHMENT_NOT_FOUND";
    public static final String ATTACHMENT_COUNT_EXCEEDED = "FLOW_ATTACHMENT_COUNT_EXCEEDED";
    public static final String ATTACHMENT_SOURCE_TASK_INVALID = "FLOW_ATTACHMENT_SOURCE_TASK_INVALID";
    public static final String ATTACHMENT_STORAGE_FAILED = "FLOW_ATTACHMENT_STORAGE_FAILED";
    public static final String REJECT_TARGET_NOT_ALLOWED = "FLOW_REJECT_TARGET_NOT_ALLOWED";
    public static final String WITHDRAW_HISTORY_NOT_FOUND = "FLOW_WITHDRAW_HISTORY_NOT_FOUND";
    public static final String WITHDRAW_PERMISSION_DENIED = "FLOW_WITHDRAW_PERMISSION_DENIED";
    public static final String DIRECT_SEND_SOURCE_NOT_FOUND = "FLOW_DIRECT_SEND_SOURCE_NOT_FOUND";
    public static final String TARGET_USER_NOT_FOUND = "FLOW_TARGET_USER_NOT_FOUND";
    public static final String ADD_SIGN_CONTEXT_INVALID = "FLOW_ADD_SIGN_CONTEXT_INVALID";
    public static final String GROUPED_TASK_ACTION_NOT_SUPPORTED = "FLOW_GROUPED_TASK_ACTION_NOT_SUPPORTED";
    public static final String TASK_ALREADY_CLAIMED = "FLOW_TASK_ALREADY_CLAIMED";
    public static final String TASK_NOT_CLAIMED = "FLOW_TASK_NOT_CLAIMED";
    public static final String TASK_CLAIM_PERMISSION_DENIED = "FLOW_TASK_CLAIM_PERMISSION_DENIED";
    public static final String REMINDER_TARGET_EMPTY = "FLOW_REMINDER_TARGET_EMPTY";
    public static final String ALERT_NOT_FOUND = "FLOW_ALERT_NOT_FOUND";
    public static final String ALERT_ALREADY_CLOSED = "FLOW_ALERT_ALREADY_CLOSED";
    public static final String REMINDER_FAILED = "FLOW_REMINDER_FAILED";
    public static final String CONDITION_EXPRESSION_INVALID = "FLOW_RUNTIME_CONDITION_EXPRESSION_INVALID";
    public static final String DEFINITION_NOT_EDITABLE = "FLOW_DEFINITION_NOT_EDITABLE";
    public static final String DEFINITION_VERSION_CONFLICT = "FLOW_DEFINITION_VERSION_CONFLICT";
    public static final String DEFINITION_CONCURRENT_MODIFIED = "FLOW_DEFINITION_CONCURRENT_MODIFIED";
    public static final String DEFINITION_IN_USE = "FLOW_DEFINITION_IN_USE";
    public static final String NODE_CODE_DUPLICATED = "FLOW_NODE_CODE_DUPLICATED";
    public static final String EDGE_CODE_DUPLICATED = "FLOW_EDGE_CODE_DUPLICATED";
    public static final String DEFINITION_STATUS_COMBINATION_INVALID = "FLOW_FROZEN_DEFINITION_STATUS_COMBINATION_INVALID";
    public static final String DEFINITION_GRAY_RULE_REQUIRED = "FLOW_FROZEN_DEFINITION_GRAY_RULE_REQUIRED";
    public static final String INSTANCE_STATUS_TRANSITION_INVALID = "FLOW_FROZEN_INSTANCE_STATUS_TRANSITION_INVALID";
    public static final String TASK_STATUS_TRANSITION_INVALID = "FLOW_FROZEN_TASK_STATUS_TRANSITION_INVALID";
    public static final String TASK_GROUP_STATUS_TRANSITION_INVALID = "FLOW_FROZEN_TASK_GROUP_STATUS_TRANSITION_INVALID";
    public static final String TASK_GROUP_COUNT_INVALID = "FLOW_FROZEN_TASK_GROUP_COUNT_INVALID";
    public static final String TASK_GROUP_BRANCH_ARRIVAL_INVALID = "FLOW_FROZEN_TASK_GROUP_BRANCH_ARRIVAL_INVALID";
    public static final String OPERATION_STATUS_TRANSITION_INVALID = "FLOW_FROZEN_OPERATION_STATUS_TRANSITION_INVALID";
    public static final String MODEL_START_NODE_INVALID = "FLOW_FROZEN_MODEL_START_NODE_INVALID";
    public static final String MODEL_END_NODE_REQUIRED = "FLOW_FROZEN_MODEL_END_NODE_REQUIRED";
    public static final String MODEL_NODE_REFERENCE_INVALID = "FLOW_FROZEN_MODEL_NODE_REFERENCE_INVALID";
    public static final String MODEL_EDGE_REFERENCE_INVALID = "FLOW_FROZEN_MODEL_EDGE_REFERENCE_INVALID";
    public static final String MODEL_USER_TASK_APPROVER_REQUIRED = "FLOW_FROZEN_MODEL_USER_TASK_APPROVER_REQUIRED";
    public static final String MODEL_GATEWAY_DEFAULT_EDGE_INVALID = "FLOW_FROZEN_MODEL_GATEWAY_DEFAULT_EDGE_INVALID";
    public static final String MODEL_PARALLEL_GATEWAY_PAIR_INVALID = "FLOW_FROZEN_MODEL_PARALLEL_GATEWAY_PAIR_INVALID";
    public static final String MODEL_ORPHAN_NODE_INVALID = "FLOW_FROZEN_MODEL_ORPHAN_NODE_INVALID";
    public static final String MODEL_NODE_OUTGOING_EDGE_INVALID = "FLOW_FROZEN_MODEL_NODE_OUTGOING_EDGE_INVALID";
    public static final String MODEL_GATEWAY_NODE_CONFIGURATION_INVALID = "FLOW_FROZEN_MODEL_GATEWAY_NODE_CONFIGURATION_INVALID";
    public static final String MODEL_MULTI_INSTANCE_CONFIGURATION_INVALID = "FLOW_FROZEN_MODEL_MULTI_INSTANCE_CONFIGURATION_INVALID";
    public static final String MODEL_CONDITION_EXPRESSION_INVALID = "FLOW_FROZEN_MODEL_CONDITION_EXPRESSION_INVALID";
    public static final String MODEL_TASK_ACTION_RULE_INVALID = "FLOW_FROZEN_MODEL_TASK_ACTION_RULE_INVALID";
    public static final String MODEL_TIMEOUT_CONFIGURATION_INVALID = "FLOW_FROZEN_MODEL_TIMEOUT_CONFIGURATION_INVALID";
    public static final String MODEL_EXCLUSIVE_GATEWAY_TOPOLOGY_INVALID = "FLOW_FROZEN_MODEL_EXCLUSIVE_GATEWAY_TOPOLOGY_INVALID";
    public static final String MODEL_PARALLEL_GATEWAY_TOPOLOGY_INVALID = "FLOW_FROZEN_MODEL_PARALLEL_GATEWAY_TOPOLOGY_INVALID";
    public static final String MODEL_GRAPH_CYCLE_INVALID = "FLOW_FROZEN_MODEL_GRAPH_CYCLE_INVALID";
    public static final String MODEL_FORM_FIELD_INVALID = "FLOW_FROZEN_MODEL_FORM_FIELD_INVALID";
    public static final String MODEL_ATTACHMENT_CONFIGURATION_INVALID = "FLOW_FROZEN_MODEL_ATTACHMENT_CONFIGURATION_INVALID";
    public static final String FORM_FIELD_REQUIRED = "FLOW_FORM_FIELD_REQUIRED";
    public static final String FORM_FIELD_CODE_DUPLICATED = "FLOW_FORM_FIELD_CODE_DUPLICATED";
    public static final String FORM_FIELD_TYPE_INVALID = "FLOW_FORM_FIELD_TYPE_INVALID";
    public static final String FORM_FIELD_CONTROL_TYPE_INVALID = "FLOW_FORM_FIELD_CONTROL_TYPE_INVALID";
    public static final String FORM_FIELD_SORT_ORDER_INVALID = "FLOW_FORM_FIELD_SORT_ORDER_INVALID";
    public static final String FORM_FIELD_VALIDATION_RULE_INVALID = "FLOW_FORM_FIELD_VALIDATION_RULE_INVALID";
    public static final String FORM_FIELD_DEFAULT_VALUE_INVALID = "FLOW_FORM_FIELD_DEFAULT_VALUE_INVALID";
    public static final String ATTACHMENT_TEMPLATE_REQUIRED = "FLOW_ATTACHMENT_TEMPLATE_REQUIRED";
    public static final String ATTACHMENT_TEMPLATE_EXTENSION_INVALID = "FLOW_ATTACHMENT_TEMPLATE_EXTENSION_INVALID";
    public static final String ATTACHMENT_TEMPLATE_SIZE_INVALID = "FLOW_ATTACHMENT_TEMPLATE_SIZE_INVALID";
    public static final String ATTACHMENT_TEMPLATE_STATUS_INVALID = "FLOW_ATTACHMENT_TEMPLATE_STATUS_INVALID";
    public static final String ATTACHMENT_TEMPLATE_NOT_FOUND = "FLOW_ATTACHMENT_TEMPLATE_NOT_FOUND";
    public static final String ATTACHMENT_TEMPLATE_REFERENCED = "FLOW_ATTACHMENT_TEMPLATE_REFERENCED";
    public static final String ATTACHMENT_TEMPLATE_VERSION_CONFLICT = "FLOW_ATTACHMENT_TEMPLATE_VERSION_CONFLICT";
    public static final String ATTACHMENT_CONFIG_REQUIRED = "FLOW_ATTACHMENT_CONFIG_REQUIRED";
    public static final String ATTACHMENT_CONFIG_TEMPLATE_INVALID = "FLOW_ATTACHMENT_CONFIG_TEMPLATE_INVALID";
    public static final String ATTACHMENT_CONFIG_TEMPLATE_DISABLED = "FLOW_ATTACHMENT_CONFIG_TEMPLATE_DISABLED";
    public static final String ATTACHMENT_CONFIG_QUANTITY_INVALID = "FLOW_ATTACHMENT_CONFIG_QUANTITY_INVALID";
    public static final String ATTACHMENT_CONFIG_NODE_INVALID = "FLOW_ATTACHMENT_CONFIG_NODE_INVALID";
    public static final String ATTACHMENT_CONFIG_DUPLICATED = "FLOW_ATTACHMENT_CONFIG_DUPLICATED";
    public static final String ATTACHMENT_CONFIG_SORT_ORDER_INVALID = "FLOW_ATTACHMENT_CONFIG_SORT_ORDER_INVALID";

    private PlatformErrorCodes() {
    }
}
